In [84]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [130]:
v = np.array ([[1,-1], [6,4]])
w = np.array([1,3])

# kita bisa tau eigenvalue dari perkalian dot product dari matriks dikali eigen vector
# maka akan menghasilkan perkalian matriks dengan eigen vector
p = v@w
p

array([-2, 18])

In [144]:
# (A - lamdaI) akan menghasilkan lamda2 - 5lamda +10 = 0
# lamda = x
# Menyelesaikan persamaan kuadrat x2 - 5x + 10 = 0
# Input koefisien dari keyboard
a = 1
b = -5
c = 10
# hitung diskriminan d
d = (b**2) - (4*a*c)
# menemukan x1 dan x2
x1 = (-b+np.lib.scimath.sqrt(d))/(2*a)
x2 = (-b-np.lib.scimath.sqrt(d))/(2*a)
print("maka eigen value adalah = ", x1, x2)

maka eigen value adalah =  (2.5+1.9364916731037085j) (2.5-1.9364916731037085j)


In [98]:
eig_val, eig_vec = np.linalg.eig(v)

In [99]:
eig_val


array([2.5+1.93649167j, 2.5-1.93649167j])

In [149]:
print("makan nilai eigen vectornya = \n", eig_vec)

makan nilai eigen vectornya = 
 [[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]


In [101]:
eig_val.real

array([2.5, 2.5])

In [102]:
eig_vec.real

array([[-0.23145502, -0.23145502],
       [ 0.9258201 ,  0.9258201 ]])