In [9]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

## **Non Graded Challenge 5 - Linear Algebra - Eigendecomposition**

### Assignment Instructions

Apakah [1, 3] adalah eigenvector dari [[ 1, -1], [ 6,  4]] Jika iya, berapakah eigenvalue-nya 

### Answer

In [18]:
print("Formula to of eigen-vector and eigen-value \n")
print("A⋅x = λx") 


Formula to of eigen-vector and eigen-value 

A⋅x = λx


In [19]:
print("So, if we want to get eigen-value :\n")

print("λ = A⋅x/x")

So, if we want to get eigen-value :

λ = A⋅x/x


In [20]:
v = np.array ([[1,-1], [6,4]]) # Matriks
w = np.array([1,3]) # Eigen Vector

# kita bisa tau eigenvalue dari perkalian dot product dari matriks dikali eigen vector
# maka akan menghasilkan perkalian matriks dengan eigen vector
p = v@w/w
p

array([-2.,  6.])

In [21]:
v

array([[ 1, -1],
       [ 6,  4]])

In [22]:
w

array([1, 3])

In [23]:
# Conclusion
print("**Conclusion**\n")
print("Because it display -2 and 6, we can say that [1, 3] is not eigen vector of [[1, -1], [6, 4]]")

**Conclusion**

Because it display -2 and 6, we can say that [1, 3] is not eigen vector of [[1, -1], [6, 4]]


In [11]:
# (A - lamdaI) akan menghasilkan lamda2 - 5lamda +10 = 0
# lamda = x
# Menyelesaikan persamaan kuadrat x2 - 5x + 10 = 0
# Input koefisien dari keyboard
a = 1
b = -5
c = 10
# hitung diskriminan d
d = (b**2) - (4*a*c)
# menemukan x1 dan x2
x1 = (-b+np.lib.scimath.sqrt(d))/(2*a)
x2 = (-b-np.lib.scimath.sqrt(d))/(2*a)
print("maka eigen value adalah = ", x1, x2)

maka eigen value adalah =  (2.5+1.9364916731037085j) (2.5-1.9364916731037085j)


In [12]:
eig_val, eig_vec = np.linalg.eig(v)

In [13]:
eig_val


array([2.5+1.93649167j, 2.5-1.93649167j])

In [6]:
print("makan nilai eigen vectornya = \n", eig_vec)

makan nilai eigen vectornya = 
 [[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]


In [7]:
eig_val.real

array([2.5, 2.5])

In [8]:
eig_vec.real

array([[-0.23145502, -0.23145502],
       [ 0.9258201 ,  0.9258201 ]])