## MATRIX

In [1]:
import pandas as pd
import numpy as np

In [4]:
A = np.array([[1,2,3], 
        [4,5,6], 
        [7,8,9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 2 Dimensi
A.shape

(3, 3)

In [6]:
# vektor
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
# 1 Dimensi
a.shape

(3,)

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
hasil = A @ np.eye(3)
hasil

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A[1, -1]

6

In [20]:
# mengambil matriks kolom 3
A[:, 2]

array([3, 6, 9])

In [21]:
# mengambil diagonal matrix
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [22]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Operasi Aritmatika

# **Penjumlahan**

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
B = np.array([[1,0,1],
              [4,0,2],
              [0,1,1]])
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [28]:
# penjumlahan matriks terhadap skalar 
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [29]:
# penjumlahan matriks terhadap matriks
A + B

array([[ 2,  2,  4],
       [ 8,  5,  8],
       [ 7,  9, 10]])

In [30]:
v = np.array([1,2,2])
A+v

array([[ 2,  4,  5],
       [ 5,  7,  8],
       [ 8, 10, 11]])

## **pengurangan**

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [31]:
# pengurangan matriks terhadap skalar
A -5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [33]:
# pengurangan matriks terhadap matriks
A - B

array([[0, 2, 2],
       [0, 5, 4],
       [7, 7, 8]])

## **pembagian**

In [40]:
print(A)
print("\n", B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 0 1]
 [4 0 2]
 [0 1 1]]


In [37]:
# pembagian matriks terhadap skalar
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [41]:
# pembagian matriks terhadap matriks
A / B

<ipython-input-41-4fe9c930694d>:2: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[ 1., inf,  3.],
       [ 1., inf,  3.],
       [inf,  8.,  9.]])

# **perkalian**

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [46]:
# perkalian matriks terhadap skalar
A * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
# perkalian hadamard product (element -wise multiplication) simbol *
A * B

array([[ 1,  0,  3],
       [16,  0, 12],
       [ 0,  8,  9]])

In [50]:
# perkalian matriks, (@)
A1 = np.array ([[1,2,1],
            [3,0,1],
            [1,0,0]])
B1 = np.array([[0,1],
        [3,1],
        [1,0]])

In [43]:
A1

array([[1, 2, 1],
       [3, 0, 1],
       [1, 0, 0]])

In [44]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [45]:
A1 @ B1

array([[7, 3],
       [1, 3],
       [0, 1]])

# **Transpose**

In [51]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [54]:
B1.T

array([[0, 3, 1],
       [1, 1, 0]])

## **Inverse**

In [55]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.linalg.inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [57]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [59]:
inv_B = np.linalg.inv(B)
inv_B

array([[-1. ,  0.5,  0. ],
       [-2. ,  0.5,  1. ],
       [ 2. , -0.5,  0. ]])

In [61]:
# matriks yang di kalikan dot product dengan linear aljebra 
# menjadi matriks identitas
B @ inv_B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
D = np.array([[1,2,1],
            [2,4,1],
            [5,7,4]])
D

array([[1, 2, 1],
       [2, 4, 1],
       [5, 7, 4]])

In [74]:
np.linalg.inv(D)

array([[-3.        ,  0.33333333,  0.66666667],
       [ 1.        ,  0.33333333, -0.33333333],
       [ 2.        , -1.        ,  0.        ]])

# **Determinant**

In [66]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [65]:
np.linalg.det(B)

2.0

In [71]:
D

array([[1, 2, 1],
       [2, 4, 1],
       [5, 7, 4]])

In [72]:
np.linalg.det(D)

-2.9999999999999996

## **Tensor**

In [79]:
M1 = np.array([[1,5,3],
            [2,7,3]])
M2 = np.array([[4,8,3],
            [9,7,7]])
M3 = np.array([[2,1,0],
             [3,0,4]])
M4 = np.array([[5,8,5],
              [9,1,7]])

In [80]:
T = np.array([M1, M2, M3, M4])
T

array([[[1, 5, 3],
        [2, 7, 3]],

       [[4, 8, 3],
        [9, 7, 7]],

       [[2, 1, 0],
        [3, 0, 4]],

       [[5, 8, 5],
        [9, 1, 7]]])

In [83]:
print("menjadi 4 matriks, 2 baris, dan 3 kolom", T.shape)

menjadi 4 matriks, 2 baris, dan 3 kolom (4, 2, 3)
