# **MATRIX**

In [1]:
import numpy as np

In [2]:
A = np.array([
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A.shape

(3, 3)

In [4]:
# vektor
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
hasil = A @ np.eye(3)
hasil

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [8]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
A[1, -1]

6

In [10]:
A[:, 2]

array([3, 6, 9])

In [11]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [12]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## **Operasi Aritmatika**

## **penjumlahan**

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
B = np.array([[1, 0, 1],
              [4, 0, 2], 
              [0, 1, 1]])
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [15]:
# penjumlahan matriks terhadap skalar
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
# penjumlahan matriks terhadap matriks
A + B

array([[ 2,  2,  4],
       [ 8,  5,  8],
       [ 7,  9, 10]])

In [17]:
v = np.array([1, 2, 2])
A + v

array([[ 2,  4,  5],
       [ 5,  7,  8],
       [ 8, 10, 11]])

## **pengurangan**

In [18]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [20]:
# pengurangan matriks terhadap skalar
A - 5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [21]:
# pengurangan matriks terhadap matriks
A - B

array([[0, 2, 2],
       [0, 5, 4],
       [7, 7, 8]])

## **pembagian**

In [22]:
# pembagian matriks terhadap skalar
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [23]:
# pembagian matriks terhadap matriks
A / B

<ipython-input-23-4fe9c930694d>:2: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[ 1., inf,  3.],
       [ 1., inf,  3.],
       [inf,  8.,  9.]])

## **perkalian**

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [26]:
# perkalian matriks terhadap skalar
A * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [27]:
# perkalian hadamard product (element-wise multiplication)
A * B

array([[ 1,  0,  3],
       [16,  0, 12],
       [ 0,  8,  9]])

In [28]:
# perkalian matriks (@)
A1 = np.array([[1, 2, 1],
               [3, 0, 1],
               [1, 0, 0]])

B1 = np.array([[0, 1],
               [3, 1],
               [1, 0]])

In [29]:
A1

array([[1, 2, 1],
       [3, 0, 1],
       [1, 0, 0]])

In [30]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [31]:
A1 @ B1

array([[7, 3],
       [1, 3],
       [0, 1]])

## **Transpose**

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [35]:
B1.T

array([[0, 3, 1],
       [1, 1, 0]])

## **Inverse**

In [36]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.linalg.inv(A) # error singular matrix

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [38]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [39]:
inv_B = np.linalg.inv(B)
inv_B

array([[-1. ,  0.5,  0. ],
       [-2. ,  0.5,  1. ],
       [ 2. , -0.5,  0. ]])

In [40]:
B @ inv_B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
D = np.array([[1, 2, 1],
              [2, 4, 2],
              [5, 7, 4]])

D

array([[1, 2, 1],
       [2, 4, 2],
       [5, 7, 4]])

In [42]:
np.linalg.inv(D) # error singular matrix, karena determinan bernilai 0

LinAlgError: Singular matrix

## **determinant**

In [ ]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
np.linalg.det(B)

2.0

In [ ]:
D

array([[1, 2, 1],
       [2, 4, 2],
       [5, 7, 4]])

In [44]:
np.linalg.det(D)

0.0

In [43]:
np.linalg.inv(D) # error singular matrix, karena determinan bernilai 0

LinAlgError: Singular matrix

## **Tensor**

In [ ]:
M1 = np.array([[1, 5, 3],
               [2, 7, 3]])

M2 = np.array([[4, 8, 3],
               [9, 7, 7]])

M3 = np.array([[2, 1, 0],
               [3, 0, 4]])

M4 = np.array([[5, 8, 5],
               [9, 1, 7]])

In [ ]:
T = np.array([M1, M2, M3, M4])
T

array([[[1, 5, 3],
        [2, 7, 3]],

       [[4, 8, 3],
        [9, 7, 7]],

       [[2, 1, 0],
        [3, 0, 4]],

       [[5, 8, 5],
        [9, 1, 7]]])

In [ ]:
T.shape

(4, 2, 3)

shape 4,2,3 -> consist of 4 matrices; each has 2 rows and 3 columns