In [3]:
import numpy as np
M1 = np.array([[23, 50],
            [7, 12]])
M2 = np.array([[17, 21],
            [57, 12]])
M3 = np.array([[57, 67],
             [99, 43]])
M4 = np.array([[87, 26],
              [18,84]])
T = np.array([M1, M2, M3, M4])
T

array([[[23, 50],
        [ 7, 12]],

       [[17, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

In [17]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])
B = np.array([[17],[22],[19]])

print(A*B, "Perkalian hadamard product\n")
print(A@B, "Perkalian dot product")

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]] Perkalian hadamard product

[[1852]
 [2454]
 [4305]] Perkalian dot product


In [20]:
T = A.T
T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [24]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [22]:
det = np.linalg.det(A)
det

131344.0000000002

In [23]:
inv = np.linalg.inv(A)
inv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])