## Latihan Numpy 


In [88]:
#Import Library
import numpy as np


In [90]:
# Perubahan dari List ke Array
# np.array()

a = [1,2,3,4,5]
print(a)
print(type(a))

b = np.array(a)
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [91]:
# Membuat Array 2D
# Lihat seberapa banyak kurung siku di awal untuk menentukan jumlah dimensi

c = [[1,2,3],
     [3,4,5]]

c = np.array(c)
c

array([[1, 2, 3],
       [3, 4, 5]])

In [95]:
#Menentukan ukuran suatu array
#.shape
print(c)
print(c.shape)
print(b)
print(b.shape)


[[1 2 3]
 [3 4 5]]
(2, 3)
[1 2 3 4 5]
(5,)


In [98]:
#Menentukan jumlah total elemen suatu array
#.size

print(b)
print(b.size)
print(c)
print(c.size)


[1 2 3 4 5]
5
[[1 2 3]
 [3 4 5]]
6


In [105]:
#Indexing & Slicing
print(b)
print(b[0:1])
print(b[::])
print(b[::2])

print(b[1::2])


#Mengubah urutan array 1D dari belakang ke depan (Descending)
print(b[::-1])


[1 2 3 4 5]
[1]
[1 2 3 4 5]
[1 3 5]
[2 4]
[5 4 3 2 1]


**NOMOR 1**

Buatlah sebuah array seperti dibawah ini dan tambahkan setiap elemennya dengan `1`.

```
a = [10, 20, 30, 40, 50]
```

In [107]:
#Cara 1 : Menambahkan dengan bil. skalar
a = [10, 20, 30, 40, 50]

a = np.array(a)
a
print(a+1)

[11 21 31 41 51]


In [110]:
# Cara 2 : Menambahkan dengan "Special Array"
#np.ones()
np.ones(4)
np.zeros(4)

a+np.ones(5)


array([11., 21., 31., 41., 51.])

**NOMOR 2**

Buatlah sebuah array seperti dibawah ini dan keluarkan element yang bernilai negatif.

```
b = [-3, 0, -2, 1, 2, 3, -4]
```

In [111]:
#Buat array
b = [-3, 0, -2, 1, 2, 3, -4]
b = np.array(b)
b

array([-3,  0, -2,  1,  2,  3, -4])

In [112]:
# Jika `b < 0` maka hanya akan dilakukan pengecekan apakah element di `b` kurang dari 0 atau tidak

b<0

array([ True, False,  True, False, False, False,  True])

In [113]:
# Jika `b[b < 0]` maka element di `b` kurang dari 0 akan ditampilkan

b[b<0]

array([-3, -2, -4])

**NOMOR 3**

Buatlah sebuah array seperti dibawah ini. Keluarkan element yang bernilai positif kemudian urutkan dari nilai yang kecil ke besar

```
c = [10, -8, 4, 5, -41, 7, 5, -4]
```

In [114]:
#Buat array

c = [10, -8, 4, 5, -41, 7, 5, -4]
c = np.array(c)
c

array([ 10,  -8,   4,   5, -41,   7,   5,  -4])

In [120]:
# Sort elemen dari bilangan kecil ke besar
#np.sort(nama_array)

c_sort = np.sort(c[c>0])


array([ 4,  5,  5,  7, 10])

In [121]:
# Sort elemen dari bilangan besar ke kecil
#sort dan Slicing dengan step = -1

print(np.sort(c[c>0])[::-1])
print(c_sort[::-1])


[10  7  5  5  4]
[10  7  5  5  4]


**NOMOR 4**

Buatlah array seperti dibawah ini kemudian tumpukkan secara horizontal dan vertikal satu sama lain.

```
d = [1, 2, 3, 4, 5]
e = [6, 7, 8, 9, 10]
```

In [122]:
#Buat array
d = [1, 2, 3, 4, 5]
e = [6, 7, 8, 9, 10]

d = np.array(d)
e = np.array(e)
print(d,e)

[1 2 3 4 5] [ 6  7  8  9 10]


In [126]:
#Stacking Horizontal -> np.hstack((array1,array2))
#Stacking Vertikal -> np.vstack((array1,array2))

print(np.hstack((d,e)))
print(np.vstack((d,e)))


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**NOMOR 5**

Buatlah dua buah array seperti dibawah ini yang berasal dari 1 deklarasi variabel yang sama. Kemudian, kalikan array pertama dengan `2` dan kalikan array kedua dengan `3`.

```
f = [10, 20, 30, 40, 50]
```

Ekspektasi output : 
```
hasil perkalian dengan 2 -> [20, 40, 60, 80, 100] 
hasil perkalian dengan 3 -> [30, 60, 90, 120, 150]
```

In [127]:
#Buat array f

f = [10, 20, 30, 40, 50]
f = np.array(f)
f

array([10, 20, 30, 40, 50])

In [129]:
#Copy array f ke variabel baru

f2 = f.copy()

In [130]:
#Kalikan masing2 variabel
f = f*2
print(f)
f2 = f2*3
print(f2)


[ 20  40  60  80 100]
[ 30  60  90 120 150]


**NOMOR 6**

Buatlah sebuah array seperti dibawah ini dan hitung total jumlahnya.

```
h = [1, 2, 3, 4, 5]
j = [ [1, 2, 3],
      [4, 5, 6]]
```

Ekspektasi output :

```
total nilai h = 15
total nilai j berdasarkan penjumlahan baris = [6, 15]
total nilai j berdasarkan penjumlahan kolom = [5, 7, 9]
```

In [131]:
#Buat array

h = [1, 2, 3, 4, 5]
j = [ [1, 2, 3],
      [4, 5, 6]]

h = np.array(h)
print(h)
j = np.array(j)
print(j)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [132]:
#jumlahkan array h
#.sum()
h.sum()


15

In [133]:
#Penjumlahan berdasarkan baris
#baris -> axis = 1
j.sum(axis = 1)


array([ 6, 15])

In [134]:
#Penjumlahan berdasarkan kolom
# kolom -> axis = 0

j.sum(axis = 0)


array([5, 7, 9])

**NOMOR 7**

Buatlah sebuah array seperti dibawah ini dan cari nilai `min`, `max`, dan `sum` per baris dan per kolom.

```
k = [ [1, 2, 3],
      [4, 5, 6]]
```

In [135]:
#Buat array
k = [ [1, 2, 3],
      [4, 5, 6]]
k = np.array(k)


In [136]:
#Mencari nilai minimum -> .min()
#Mencari nilai maximum - > .max()
#Mencari nilai total -> .sum()

print('Baris')
print(k.min(axis = 1), 'nilai minimum')
print(k.max(axis = 1), 'nilai maksimum')
print(k.sum(axis = 1), 'nilai total')

print('\nKolom')
print(k.min(axis = 0), 'nilai minimum')
print(k.max(axis = 0), 'nilai maksimum')
print(k.sum(axis = 0), 'nilai total')



Baris
[1 4] nilai minimum
[3 6] nilai maksimum
[ 6 15] nilai total

Kolom
[1 2 3] nilai minimum
[4 5 6] nilai maksimum
[5 7 9] nilai total


**NOMOR 8**

Buatlah sebuah array seperti dibawah ini dan cari baris kedua dan kolom kedua.

```
n = [ [1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]
```

In [137]:
#Buat array

n = [ [1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]

n = np.array(n)
n


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
#Get baris&Kolom
# nama_array[baris,kolom]
print(n[1,:])

n[1,1]
n[2,2]
n[0,0]
n[2,1]

[4 5 6]


8

In [153]:
# Get baris kedua
# Bisa menggunakan n[1] atau n[1, :]

print(n[1])
print(n[1,:])

[4 5 6]
[4 5 6]


In [145]:
# Get kolom kedua (menampilkan secara array 1D)
# nama_array[:, [index_kolom]]

n[:,1]

array([2, 5, 8])

In [147]:
# Get elemen diagonal (dari kiri ke kanan)
# np.diag()
# buka dokumentasi

np.diag(np.diag(n))


array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [152]:
# Get elemen diagonal (dari kanan ke kiri)
# np.diag(np.fliplr(n))

np.diag(np.fliplr(n))


array([3, 5, 7])

**NOMOR 9**

Buatlah sebuah array seperti dibawah ini dan cari nilai `min`, `max`, dan `sum` untuk baris kedua dan kolom kedua.

```
m = [ [1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]
```

In [73]:
#Buat array


In [74]:
#buat variabel yang berisikan baris ke 2

#buat variabel yang berisikan kolom ke 2


In [75]:
#Cari masing2 nilai sum, min, dan max


**NOMOR 10**

<img src='https://i.ibb.co/JvBzgWn/greyscale.png'>

Download image [disini](https://i.ibb.co/JvBzgWn/greyscale.png)

* Load gambar tersebut dengan menggunakan library matplotlib.
* Jawab pertanyaan berikut ini : 
  - Berapa ukuran gambar tersebut.
  - Berapa total piksel/element pada gambar tersebut.
  - Cerahkan gambar tersebut dengan menambahkan suatu angka.

In [76]:
#Install matplotlib in jupyter
import sys  
!{sys.executable} -m pip install --user matplotlib

You should consider upgrading via the 'C:\Users\ACER\AppData\Local\Programs\Python\Python37\python.exe -m pip install --upgrade pip' command.


In [77]:
#Import matplotlib

import matplotlib.pyplot as plt

In [78]:
#Baca gambar menggunakan plt.imread('location_gambar') lalu masukkan ke variabel



In [79]:
#Cek ukuran gambar
#.shape


In [80]:
# Total Piksel
#.size


In [81]:
#Nilai piksel
#img, udah di scalling


In [82]:
#Memastikan tipe data menjadi array
#np.asarray()



In [83]:
#Menentukan nilai yg akan ditambahkan ke piksel
#Ubah ke skala 0-1, divide by 255 (highest pixel value)



In [84]:
#Copy datanya dulu (penting setiap ingin memodifikasi data) ke variabel baru

#tambahkan nilai piksel ke gambar


In [85]:
# Menampilkan gambar original
# `img` : array gambar
# `cmap` : color map #figure
# `vmin` : value minimum #figure
# `vmax` : value maximum #figure
#plt.imshow(nama_variabel, cmap='gray', vmin=0, vmax=1)



In [86]:
# Menampilkan gambar yg sudah ditambah suatu value
